sudo: false
dist: xenial
language: php

services:
  - mysql

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

matrix:
  fast_finish: true

before_script:
  - git clone --depth=50 --branch=2020.10 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core && mv ../ai-controller-jobs ext/
  - travis_retry composer update
  - mysql -e "CREATE DATABASE aimeos; GRANT ALL ON aimeos.* TO 'aimeos'@'127.0.0.1' IDENTIFIED BY 'aimeos'"
  - echo "<?php return array( 'db' => array( 'adapter' => 'mysql', 'host' => '127.0.0.1', 'database' => 'aimeos', 'username' => 'aimeos', 'password' => 'aimeos', 'limit' => 2, 'opt-persistent' => false, 'stmt' => array( \"SET SESSIOn sort_buffer_size=2097144; SET NAMES 'utf8'; SET SESSION sql_mode='ANSI'\" ) ), 'mq' => array( 'adapter' => 'Standard', 'db' => 'db' ) );" > config/resource.php

script:
  - vendor/bin/phing -Ddir=ext/ai-controller-jobs setup coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-controller-jobs/.coveralls.yml
